sudo: false

language:
  node_js

branches:
  only:
    - master

cache:
  directories:
    - node_modules

matrix:
  include:
  - name: "Node 8 Test"
    node_js: "8"
  - name: "Node 9 Test"
    node_js: "9"
  - name: "Node 10 Test"
    node_js: "10"
script: yarn test:ci

# jobs:
#   include:
#     - stage: test
#       matrix:
#         include:
#         - name: "Node 8 Test"
#           node_js: "8"
#         - name: "Node 9 Test"
#           node_js: "9"
#         - name: "Node 10 Test"
#           node_js: "10"
#       script: yarn test:ci
#     - stage: 'Package Update Check'
#       if: type = cron
#       script:
#         - yarn outdated-notifier --api-token $GITHUB_REPO
