sudo: false

language:
  node_js

branches:
  only:
    - master

# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#caching-with-yarn
cache: yarn
stages:
  - name: lint
    if: branch = master AND type = pull_request
  - name: compile
    if: branch = master AND type = pull_request
  - name: test
    if: branch = master AND type = pull_request
  # https://docs.travis-ci.com/user/conditions-v1
  - name: deploy
    if: branch = master AND type = push

jobs:
  include:
    - stage: lint
      script: yarn run lint
      node_js:
      - "10"
    - stage: compile
      script: yarn build
      node_js:
      - "10"
    - stage: test
      script: yarn test
      node_js:
      - "8"
      - "9"
      - "10"
    - stage: deploy
      script: ./scripts/deploy.sh
      node_js:
      - "10"
