sudo: false
branches:
  only:
    - master

language:
  node_js

node_js:
  - '8'

script:
  yarn test:ci

jobs:
  include:
    - stage: 'Package Update Check'
      if: type = cron
      script:
        - yarn outdated-notifier --api-token $GITHUB_REPO

